const I18N_LANGS=["es","en"];
const I18N_DEFAULT=SITE_CONFIG.defaultLanguage||"es";
const I18N_LABELS={es:"Español",en:"English"};
const I18N_FLAGS={es:"Assets/flag-es.svg",en:"Assets/flag-en.svg"};
const I18N={
 es:{"nav.home":"Inicio","nav.validator":"Validador","nav.contact":"Contactar","hero.tagline":"Portal de Documentación para Desarrolladores","hero.title1":"Facturación electrónica B2B","hero.title2":"Spain e-Invoicing","hero.subtitle":"Documentación técnica para los estándares JSON, XML, respuestas, estados y documentación AEAT.","hero.cta.docs":"Explorar documentación","hero.cta.validator":"Abrir validador","stats.sections":"Secciones documentales","stats.lang":"Multilenguaje","home.eyebrow":"Centro de documentación · E-Invoicing","home.title":"Estándares y recursos de integración","home.subtitle":"Selecciona una sección para consultar sus readmes, ejemplos, esquemas y documentación relacionada.","crumb.docs":"Documentación","crumb.validator":"Validador","tabs.readme":"Readme","tabs.files":"Ficheros","footer.desc":"Documentación técnica de facturación electrónica · Generix Spain.","footer.bottom2":"Especificaciones técnicas e integración e-Invoicing","file.view":"Ver contenido","file.hide":"Ocultar","file.download":"Descargar","file.open":"Abrir","file.copy":"Copiar","file.copied":"✓ Copiado","readme.missing":"No se ha encontrado el README para esta sección todavía.","readme.missingHint":"Crea el fichero readme.es.md/readme.en.md en la ruta configurada.","loading":"Cargando…","validator.h1":"Validador JSON","validator.desc":"Selecciona una sección con schema JSON y valida tu fichero local contra el esquema configurado.","validator.label":"Schema a validar","validator.drop.disabled":"Selecciona primero un schema y luego arrastra tu JSON o haz click","validator.drop.enabled":"Arrastra tu JSON o haz click","validator.select":"— Selecciona un schema —","validator.valid":"JSON válido","validator.invalid":"JSON inválido","validator.syntax":"JSON inválido: error de sintaxis","validator.schemaLoad":"No se pudo cargar el schema","validator.wait":"Esperando validación","validator.waitText":"Sube un fichero para lanzar la validación.","validator.ok":"Validación completada","validator.okText":"El fichero cumple con el schema.","validator.err":"Se detectaron errores","validator.errText":"El fichero no cumple con el schema.","validator.field":"Campo","validator.error":"Error","validator.required":"Falta el campo obligatorio","validator.type":"Tipo incorrecto","validator.enum":"Valor no permitido","validator.pattern":"No cumple el patrón","validator.maxLength":"Longitud máxima excedida","validator.minLength":"Longitud mínima no alcanzada","validator.additional":"Propiedad no permitida"},
 en:{"nav.home":"Home","nav.validator":"Validator","nav.contact":"Contact","hero.tagline":"Developer Documentation Portal","hero.title1":"B2B electronic invoicing","hero.title2":"Spain e-Invoicing","hero.subtitle":"Technical documentation for JSON, XML, responses, status and AEAT documentation.","hero.cta.docs":"Explore documentation","hero.cta.validator":"Open validator","stats.sections":"Documentation sections","stats.lang":"Multilanguage","home.eyebrow":"Documentation center · E-Invoicing","home.title":"Integration standards and resources","home.subtitle":"Select a section to browse readmes, examples, schemas and related documentation.","crumb.docs":"Documentation","crumb.validator":"Validator","tabs.readme":"Readme","tabs.files":"Files","footer.desc":"E-invoicing technical documentation · Generix Spain.","footer.bottom2":"E-Invoicing technical specifications and integration","file.view":"View content","file.hide":"Hide","file.download":"Download","file.open":"Open","file.copy":"Copy","file.copied":"✓ Copied","readme.missing":"README not found for this section yet.","readme.missingHint":"Create readme.es.md/readme.en.md in the configured path.","loading":"Loading…","validator.h1":"JSON validator","validator.desc":"Select a section with a JSON schema and validate your local file against the configured schema.","validator.label":"Schema to validate","validator.drop.disabled":"First select a schema, then drag your JSON or click","validator.drop.enabled":"Drag your JSON or click","validator.select":"— Select a schema —","validator.valid":"Valid JSON","validator.invalid":"Invalid JSON","validator.syntax":"Invalid JSON: syntax error","validator.schemaLoad":"Could not load schema","validator.wait":"Waiting for validation","validator.waitText":"Upload a file to run validation.","validator.ok":"Validation completed","validator.okText":"The file complies with the schema.","validator.err":"Errors detected","validator.errText":"The file does not comply with the schema.","validator.field":"Field","validator.error":"Error","validator.required":"Missing required field","validator.type":"Wrong type","validator.enum":"Value not allowed","validator.pattern":"Pattern mismatch","validator.maxLength":"Maximum length exceeded","validator.minLength":"Minimum length not reached","validator.additional":"Additional property not allowed"}
};
function detectLang(){try{const s=localStorage.getItem(SITE_CONFIG.storageKey);if(I18N_LANGS.includes(s))return s;}catch(e){}const n=(navigator.language||I18N_DEFAULT).slice(0,2).toLowerCase();return I18N_LANGS.includes(n)?n:I18N_DEFAULT;}
let LANG=detectLang();
function t(key,vars){let s=(I18N[LANG]&&I18N[LANG][key])||(I18N[I18N_DEFAULT]&&I18N[I18N_DEFAULT][key])||key;if(vars)Object.keys(vars).forEach(k=>s=s.split("{"+k+"}").join(vars[k]));return s;}
function getLocalized(obj){if(!obj)return"";return obj[LANG]||obj[I18N_DEFAULT]||Object.values(obj)[0]||"";}
function setLang(l){if(!I18N_LANGS.includes(l))return;try{localStorage.setItem(SITE_CONFIG.storageKey,l)}catch(e){}LANG=l;applyStaticI18n();if(window.APP)window.APP.refresh();}
function applyStaticI18n(){document.documentElement.lang=LANG;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.getAttribute("data-i18n")));const sw=document.getElementById("langSwitch");if(!sw)return;const current=document.getElementById("langCurrent"),menu=document.getElementById("langMenu");const flag=l=>`<span class="lang-flag"><img src="${I18N_FLAGS[l]}" alt=""></span>`;const label=l=>`${l.toUpperCase()} · ${I18N_LABELS[l]||l}`;current.innerHTML=flag(LANG)+`<span>${label(LANG)}</span>`;menu.innerHTML=I18N_LANGS.map(l=>`<li class="lang-option${l===LANG?' active':''}" role="option" data-lang="${l}">${flag(l)}<span>${label(l)}</span></li>`).join("");const close=()=>{sw.classList.remove("open");current.setAttribute("aria-expanded","false")};current.onclick=e=>{e.stopPropagation();const open=sw.classList.toggle("open");current.setAttribute("aria-expanded",open?"true":"false")};menu.querySelectorAll(".lang-option").forEach(op=>op.onclick=e=>{e.stopPropagation();setLang(op.dataset.lang);close();});document.addEventListener("click",close,{once:true});}
window.t=t;window.getLocalized=getLocalized;window.setLang=setLang;window.applyStaticI18n=applyStaticI18n;window.LANG=()=>LANG;
